export const currencyByDinarsDz: Currency[] = [
  {
    name: 'DOLLAR',
    value: 0.00729969,
    flag: '🇺🇸',
    symbol: '$',
  },
  {
    name: 'EURO',
    value: 0.00680242,
    flag: '🇪🇺',
    symbol: '€',
  },
  {
    name: 'POUND',
    value: 0.00588541,
    flag: '🇬🇧',
    symbol: '£',
  },
  {
    name: 'RUPEE',
    value: 0.605882,
    flag: '🇮🇳',
    symbol: '₹',
  },
  {
    name: 'AUS DOLLAR',
    value: 0.0112384,
    flag: '🇦🇺',
    symbol: 'A$',
  },
  {
    name: 'CAN DOLLAR',
    value: 0.00978430,
    flag: '🇨🇦',
    symbol: 'C$',
  },
  {
    name: 'YEN',
    value: 1.07808,
    flag: '🇯🇵',
    symbol: '¥',
  },
  {
    name: 'DINAR',
    value: 0.00225129,
    flag: '🇰🇼',
    symbol: 'KD',
  },
  {
    name: 'BITCOIN',
    value: 0.000000268722,
    flag: '🎰',
    symbol: '₿',
  },
  {
    name: 'FRANC',
    value: 0.00660257,
    flag: '🇨🇭',
    symbol: 'CHF',
  },
  {
    name: 'ETHEREUM',
    value: 0.00000456807,
    flag: '🎰',
    symbol: 'Ξ',
  },
  {
    name: 'RUBLE',
    value: 0.700318 ,
    flag: '🇷🇺',
    symbol: '₽',
  },
  {
    name: 'YUAN',
    value: 0.0531581,
    flag: '🇨🇳',
    symbol: '¥',
  },
  {
    name: ' LIRA',
    value: 0.197880,
    flag: '🇹🇷',
    symbol: '₺',
  },
  {
    name: 'WON',
    value: 9.71915,
    flag: '🇰🇷',
    symbol: '₩',
  },
  {
    name: 'DINAR TN',
    value: 0.0229004,
    flag: '🇹🇳',
    symbol: 'د.ت',
  },
  {
    name: 'RAND',
    value: 0.136582,
    flag: '🇿🇦',
    symbol: 'R',
  },
  {
    name: 'HRYVNIA',
    value: 0.268572,
    flag: '🇺🇦',
    symbol: '₴',
  },
  {
    name: 'KRONE',
    value: 0.078345,
    flag: '🇳🇴',
    symbol: 'kr',
  },
  {
    name: 'ROMANIAN LEU',
    value: 0.0339555,
    flag: '🇷🇴',
    symbol: 'lei',
  },
  {
    name: 'ISK KRONA',
    value: 0.993230,
    flag: '🇮🇸',
    symbol: 'Íkr',
  },
];
